### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by etewiah** [prodsters/property_web_builder#13]
Creator of the original propertywebbuilder here.  Just curious to know what the status of this project is.

I'm working on propertywebbuilder again after a pause and would like to help any variants of it.  One think I'm thinking of is to separate the backend (which could be either rails or laravel serving an API) from the frontend (which will be a js app written with the Vue framework)

Would like to hear your thoughts.

**Comment by SeunMatt** [comment]
No active development is going on this at the moment. 
Considering the project is historically Laravel, I will suggest you write the backend in Laravel still. Overall, separating the backend from the front-end will be a plus

**Comment by etewiah** [comment]
Thanks for the quick reply.  I wrote the original project ( https://github.com/etewiah/property_web_builder ) in Ruby on Rails and I will stick with that.

I am happy to support anyone who wishes to carry on with the Laravel project though.

I will post updates on my progress here:
https://github.com/etewiah/property_web_builder/discussions/131
